export const photos = [
  {
    src: "https://i.postimg.cc/wxLvnY0M/0088.jpg",
    thumb: "images/thumbs/0088.webp",
    name: "Atypical House - Casa al revés",
    place: "El Peñol",
    city: "Guatapé",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/tJ346FsG/0087.jpg",
    thumb: "images/thumbs/0087.webp",
    name: "Isla en medio de embalse - segunda toma",
    city: "Guatapé",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/nr4hmqXb/0086.jpg",
    thumb: "images/thumbs/0086.webp",
    name: "Casa azul - segunda toma",
    city: "Guatapé",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/L5t8PjJd/0085.jpg",
    thumb: "images/thumbs/0085.webp",
    name: "Islas en medio de embalse - segunda toma",
    city: "Guatapé",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/GtFmDvHZ/0084.jpg",
    thumb: "images/thumbs/0084.webp",
    name: "Isla en medio de embalse - primera toma",
    city: "Guatapé",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/mkYg97tJ/0083.jpg",
    thumb: "images/thumbs/0083.webp",
    name: "Islas en medio de embalse - primera toma",
    city: "Guatapé",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/8cRzvLjw/0082.jpg",
    thumb: "images/thumbs/0082.webp",
    name: "Moto acuática navegando en embalse",
    city: "Guatapé",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/90dQ9yrp/0081.jpg",
    thumb: "images/thumbs/0081.webp",
    name: "Casas en península en embalse",
    city: "Guatapé",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/nr4hmqCY/0080.jpg",
    thumb: "images/thumbs/0080.webp",
    name: "Bote navegando en embalse",
    city: "Guatapé",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/1XG3FDf0/0079.jpg",
    thumb: "images/thumbs/0079.webp",
    name: "Embalse - vista aerea - segunda toma",
    place: "Piedra del Peñol",
    city: "Guatapé",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/rs1w45K4/0078.jpg",
    thumb: "images/thumbs/0078.webp",
    name: "Embalse - vista aerea - primera toma",
    place: "Piedra del Peñol",
    city: "Guatapé",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/Rh7ZtwNH/0077.jpg",
    thumb: "images/thumbs/0077.webp",
    name: "Piedra del Peñol",
    city: "Guatapé",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/QCQd7cHK/0076.jpg",
    thumb: "images/thumbs/0076.webp",
    name: "Piedra del Peñol - cima",
    city: "Guatapé",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/Zntq0wKx/0075.jpg",
    thumb: "images/thumbs/0075.webp",
    name: "Casa azul - primera toma",
    place: "Embalse",
    city: "Guatapé",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/4yk3nWNp/0074.jpg",
    thumb: "images/thumbs/0074.webp",
    name: "Muelle",
    place: "Embalse",
    city: "Guatapé",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/VvQN5KLM/0073.jpg",
    thumb: "images/thumbs/0073.webp",
    name: "Máscara Aku Aku",
    place: "Granja el Alto del Chocho",
    city: "Guatapé",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/3N5wWtJD/0072.jpg",
    thumb: "images/thumbs/0072.webp",
    name: "Camino de piedras con hortensias - segunda toma",
    city: "Jardín",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/Y0KSjdq4/0071.jpg",
    thumb: "images/thumbs/0071.webp",
    name: "Camino de piedras con hortensias - primera toma",
    city: "Jardín",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/HnDLj6sk/0070.jpg",
    thumb: "images/thumbs/0070.webp",
    name: "Entrada de luz",
    place: "Cueva del Esplendor",
    city: "Jardín",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/NFq0LdfQ/0069.jpg",
    thumb: "images/thumbs/0069.webp",
    name: "Cascada con entrada de luz",
    place: "Cueva del Esplendor",
    city: "Jardín",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/8cQCsZPD/0068.jpg",
    thumb: "images/thumbs/0068.webp",
    name: "Cascada",
    place: "Cueva del Esplendor",
    city: "Jardín",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/3N5wWtJh/0067.jpg",
    thumb: "images/thumbs/0067.webp",
    name: "Pequeña cascada",
    place: "Río Melcocho",
    city: "Jardín",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/hj7jSkgj/0066.jpg",
    thumb: "images/thumbs/0066.webp",
    name: "Camino de piedra",
    city: "Jardín",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/ZRyRTGZY/0065.jpg",
    thumb: "images/thumbs/0065.webp",
    name: "Hortensia",
    city: "Jardín",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/63G39kwp/0064.jpg",
    thumb: "images/thumbs/0064.webp",
    name: "Cruz - Mirador",
    place: "Finca",
    city: "Jardín",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/nzQzHyZc/0063.jpg",
    thumb: "images/thumbs/0063.webp",
    name: "Templo Jubilar Diocesano - Iglesia",
    place: "Parque principal",
    city: "Jardín",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/FzN14y3Q/0062.jpg",
    thumb: "images/thumbs/0062.webp",
    name: "Letrero Yo amo Guatavita",
    place: "Parque principal",
    city: "Guatavita",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/QtpVw49h/0061.jpg",
    thumb: "images/thumbs/0061.webp",
    name: "Hombre jugando tetris. CTWC",
    Event: "SOFA",
    place: "Corferias",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/SRkjh6Ch/0060.jpg",
    thumb: "images/thumbs/0060.webp",
    name: "Casa roja entre hojas",
    place: "Iglesia la Valvanera",
    city: "Chía",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/vmpfTZhF/0059.jpg",
    thumb: "images/thumbs/0059.webp",
    name: "Flor amarilla",
    place: "Comuna 13",
    city: "Medellín",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/rpd5qrSN/0058.jpg",
    thumb: "images/thumbs/0058.webp",
    name: "Escultura de Anubis",
    place: "Catedral de sal, museo Tutankamón",
    city: "Zipaquirá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/pLcDNZnd/0057.jpg",
    thumb: "images/thumbs/0057.webp",
    name: "Escaleras de piedra con halo de luz",
    place: "Catedral de sal, museo monumental 180",
    city: "Zipaquirá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/GmmkSNtN/0056.jpg",
    thumb: "images/thumbs/0056.webp",
    name: "Escultura de piedra, figura geométrica",
    place: "Catedral de sal, museo monumental 180",
    city: "Zipaquirá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/TYGjnh6T/0055.jpg",
    thumb: "images/thumbs/0055.webp",
    name: "Escultura de piedra",
    place: "Catedral de sal, museo monumental 180",
    city: "Zipaquirá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/QNckB1v6/0054.jpg",
    thumb: "images/thumbs/0054.webp",
    name: "Escultura de mujer con cabello en la cara",
    place: "Catedral de sal, museo monumental 180",
    city: "Zipaquirá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/T1jrZvr8/0053.jpg",
    thumb: "images/thumbs/0053.webp",
    name: "Árbol de la vida",
    place: "Catedral de sal",
    city: "Zipaquirá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/L5FtC8gB/0052.jpg",
    thumb: "images/thumbs/0052.webp",
    name: "Cruz color roja tallada en la pared",
    place: "Catedral de sal",
    city: "Zipaquirá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/k4bNvbGg/0051.jpg",
    thumb: "images/thumbs/0051.webp",
    name: "Cruz color roja, viacrucis",
    place: "Catedral de sal",
    city: "Zipaquirá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/Gp9x9N1Y/0050.jpg",
    thumb: "images/thumbs/0050.webp",
    name: "Manos de esperanza",
    place: "Catedral de sal",
    city: "Zipaquirá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/g2gKzp1m/0049.jpg",
    thumb: "images/thumbs/0049.webp",
    name: "Fumidzuki, mes de las letras en japonés: 文月",
    place: "Bogotá",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/VkfRPvGK/0048.jpg",
    thumb: "images/thumbs/0048.webp",
    name: "Café, libro, galletas, tablet y prensa francesa",
    place: "Bogotá",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/m2GjV8Qf/0047.jpg",
    thumb: "images/thumbs/0047.webp",
    name: "Flores y vegetación",
    place: "Carmen de Apicalá",
    city: "Carmen de Apicalá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/7PzXgpJn/0046.jpg",
    thumb: "images/thumbs/0046.webp",
    name: "Fogata de año viejo",
    place: "Bogotá",
    event: "Año viejo",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/fyYKD9Qr/0045.jpg",
    thumb: "images/thumbs/0045.webp",
    name: "Velitas con nombres",
    place: "Bogotá",
    event: "Día de velitas 2024",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/DZ9g9cHG/0044.jpg",
    thumb: "images/thumbs/0044.webp",
    name: "Torre Colpatria",
    place: "Bogotá",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/PxpyV73h/0043.jpg",
    thumb: "images/thumbs/0043.webp",
    name: "T-rex bebé en incubadora",
    place: "Planetario de Bogotá",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/BvwNg3CM/0042.jpg",
    thumb: "images/thumbs/0042.webp",
    name: "Compy",
    place: "Planetario de Bogotá",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/YSSbY0Qv/0041.jpg",
    thumb: "images/thumbs/0041.webp",
    name: "Estatua de velociraptor",
    place: "Planetario de Bogotá",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/T30tKg58/0040.jpg",
    thumb: "images/thumbs/0040.webp",
    name: "Caracara Cheriwa",
    place: "Piscilago",
    city: "Girardot",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/rwMhyQmC/0039.jpg",
    thumb: "images/thumbs/0039.webp",
    name: "Chauna Chavaria",
    place: "Piscilago",
    city: "Girardot",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/pXDGtg2L/0038.jpg",
    thumb: "images/thumbs/0038.webp",
    name: "Pato negro",
    place: "Piscilago",
    city: "Girardot",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/TY87FRvs/0037.jpg",
    thumb: "images/thumbs/0037.webp",
    name: "Águila",
    place: "Piscilago",
    city: "Girardot",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/1RV7v826/0036.jpg",
    thumb: "images/thumbs/0036.webp",
    name: "Halcón",
    place: "Piscilago",
    city: "Girardot",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/nzgRHxjC/0035.jpg",
    thumb: "images/thumbs/0035.webp",
    name: "Flamingos",
    place: "Piscilago",
    city: "Girardot",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/J0XT0FZK/0034.jpg",
    thumb: "images/thumbs/0034.webp",
    name: "Pavo real con la cola extendida en acercamiento",
    place: "Piscilago",
    city: "Girardot",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/cHrkyCJp/0033.jpg",
    thumb: "images/thumbs/0033.webp",
    name: "Pavo real con la cola extendida",
    place: "Piscilago",
    city: "Girardot",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/25H9KhCd/0032.jpg",
    thumb: "images/thumbs/0032.webp",
    name: "Gata Fogata",
    place: "Las novias del gato",
    city: "Cali",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/wjpry9WN/0031.jpg",
    thumb: "images/thumbs/0031.webp",
    name: "Santa misión",
    place: "Cali",
    city: "Cali",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/Ls40DNF6/0030.jpg",
    thumb: "images/thumbs/0030.webp",
    name: "Motocicleta hecha con alambres",
    place: "Cali",
    city: "Cali",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/MpmF1g4F/0029.jpg",
    thumb: "images/thumbs/0029.webp",
    name: "Maceta",
    place: "Cali",
    city: "Cali",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/yY958DTB/0028.jpg",
    thumb: "images/thumbs/0028.webp",
    name: "Letrero",
    place: "Parque de la 93",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/SQH346CD/0027.jpg",
    thumb: "images/thumbs/0027.webp",
    name: "Mensaje de motivación MINISO",
    place: "Parque de la 93",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/T2KFB7LK/0026.jpg",
    thumb: "images/thumbs/0026.webp",
    name: "Farolito de la Virgen María",
    place: "Bogotá",
    event: "Día de velitas 2023",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/XXMwP7Zk/0025.jpg",
    thumb: "images/thumbs/0025.webp",
    name: "Cascadas Tequendamita",
    place: "La Ceja",
    city: "Antioquia",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/WzqGSJ44/0024.jpg",
    thumb: "images/thumbs/0024.webp",
    name: "Escaleras de piedra",
    place: "Comuna 13",
    city: "Medellín",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/bJB0QRpM/0023.jpg",
    thumb: "images/thumbs/0023.webp",
    name: "Barril Ron Medellín",
    place: "Medellín",
    city: "Medellín",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/pTTYhSbz/0022.jpg",
    thumb: "images/thumbs/0022.webp",
    name: "Conjunto de vegetación y flores",
    place: "Norte de Bogotá",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/1zMrzQTy/0021.jpg",
    thumb: "images/thumbs/0021.webp",
    name: "Flor rosada",
    place: "Bogotá",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/BnTCdDBL/0020.jpg",
    thumb: "images/thumbs/0020.webp",
    name: "Edifício de Ciencia y Tecnología de noche desde la parte de en frente",
    place: "Universidad Nacional de Colombia",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/Bn9gYNHf/0019.jpg",
    thumb: "images/thumbs/0019.webp",
    name: "Edifício de Ciencia y Tecnología de noche desde la parte de atrás",
    place: "Universidad Nacional de Colombia",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/7PRX7qL6/0018.jpg",
    thumb: "images/thumbs/0018.webp",
    name: "Máquina de videojuegos Killer Instinct",
    place: "Corferias",
    Event: "SOFA",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/TYW0JByc/0017.jpg",
    thumb: "images/thumbs/0017.webp",
    name: "Estatua de demonio con armas en la espalda",
    place: "Corferias",
    Event: "SOFA",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/T1B9XJsm/0016.jpg",
    thumb: "images/thumbs/0016.webp",
    name: "Edificio Corferias junto a arco",
    place: "Corferias",
    Event: "SOFA",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/fyVKFr8D/0015.jpg",
    thumb: "images/thumbs/0015.webp",
    name: "Dos imágenes de caricaturas",
    place: "Corferias",
    Event: "SOFA",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/tTSkBjtB/0014.jpg",
    thumb: "images/thumbs/0014.webp",
    name: "Nube en forma de aureola",
    place: "Parque Simón Bolívar",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/Y9q8N9g4/0013.jpg",
    thumb: "images/thumbs/0013.webp",
    name: "Cruz",
    place: "Parque Simón Bolívar",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/DzcBbsWk/0012.jpg",
    thumb: "images/thumbs/0012.webp",
    name: "Shen Long",
    place: "Biblioteca Virgilio Barco",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/HLm6x3k9/0011.jpg",
    thumb: "images/thumbs/0011.webp",
    name: "Camino de agua",
    place: "Biblioteca Virgilio Barco",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/K8B9xCxY/0010.jpg",
    thumb: "images/thumbs/0010.webp",
    name: "Islote con árboles. Efecto ojo de pez",
    place: "Biblioteca Virgilio Barco",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/GhZ70b0N/0009.jpg",
    thumb: "images/thumbs/0009.webp",
    name: "Dos estructuras circulares dentro de un pozo de agua",
    place: "Biblioteca Virgilio Barco",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/nVSSkv3n/0008.jpg",
    thumb: "images/thumbs/0008.webp",
    name: "Lago, puente y flores moradas desde el lateral",
    place: "Biblioteca Virgilio Barco",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/m2cX6tnC/0007.jpg",
    thumb: "images/thumbs/0007.webp",
    name: "Lago, puente y flores moradas",
    place: "Biblioteca Virgilio Barco",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/BbbY36nW/0006.jpg",
    thumb: "images/thumbs/0006.webp",
    name: "Hombre con chaqueta amarilla caminando frente a la Biblioteca Virgilio Barco",
    place: "Biblioteca Virgilio Barco",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/XqP2Ybrr/0005.jpg",
    thumb: "images/thumbs/0005.webp",
    name: "Biblioteca Virgilio Barco",
    place: "Biblioteca Virgilio Barco",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/GpPSJV5f/0004.jpg",
    thumb: "images/thumbs/0004.webp",
    name: "Estatua Simon Bolívar",
    place: "Parque Simón Bolívar",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/wv64WFKj/0003.jpg",
    thumb: "images/thumbs/0003.webp",
    name: "Gazebo",
    place: "Parque Simón Bolívar",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/nz0RN7ZY/0002.jpg",
    thumb: "images/thumbs/0002.webp",
    name: "Escultura de arena",
    place: "Parque Simón Bolívar",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
  {
    src: "https://i.postimg.cc/1z1jFsJ6/0001.jpg",
    thumb: "images/thumbs/0001.webp",
    name: "Bote en lago",
    place: "Parque Simón Bolívar",
    city: "Bogotá",
    country: "CO",
    desc: "",
  },
];